### ISSUE TITLE
请问现在还更新吗？你现在是使用这个路由吗？

### ISSUE THREAD

**Issue by Samdyddd** [sunlandong/dynamicRouter#4]

**Comment by Samdyddd** [comment]
在Login.vue中发现写的不是很合理；考虑使用vuex吗？

**Comment by WeiYuanStudio** [comment]
不知道您是否想要交流关于路由方面的问题。我今天晚上折腾了很久。整个页面始终都是白的。
最后参考了几个vue-router项目。使用另一种渲染方式解决了问题。发现一个地方有点疑问。
该项目在 `main.js` 文件中的配置为

```js
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})
```

[vue-router官方文档](https://router.vuejs.org/zh/guide/#javascript)

```
const app = new Vue({
  router
}).$mount('#app')
```

而我参照了另一个项目[](https://github.com/sunlandong/dynamicRouter/blob/master/src/main.js#L43~L48) 的写法

```js
new Vue({
  router,
  store,
  render: h => h(App)
}).$mount("#app");
```

关键点 ` render: h => h(App)` 

这个渲染解决了我的问题。但是我还是不明白这里的原因。还请多多指教
